package com.meession.etm.module.bpm.service.oa;
import com.meession.etm.framework.common.util.object.BeanUtils; import com.meession.etm.module.bpm.controller.admin.oa.vo.BpmOADocumentSaveReqVO; import com.meession.etm.module.bpm.dal.dataobject.oa.*; import com.meession.etm.module.bpm.dal.mysql.oa.*; import jakarta.annotation.Resource; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*; import static com.meession.etm.framework.common.exception.util.ServiceExceptionUtil.exception; import static com.meession.etm.module.bpm.enums.ErrorCodeConstants.OA_TASK_NOT_EXISTS;
@Service public class BpmOADocumentServiceImpl implements BpmOADocumentService { @Resource private BpmOADocumentMapper mapper; @Resource private BpmOADocumentMemberMapper memberMapper; @Resource private BpmOADocumentVersionMapper versionMapper;
 @Override public Long create(Long userId,BpmOADocumentSaveReqVO req){BpmOADocumentDO row=BeanUtils.toBean(req,BpmOADocumentDO.class).setOwnerUserId(userId).setStatus(0).setCurrentVersion(0);mapper.insert(row);return row.getId();}
 @Override public void update(Long userId,BpmOADocumentSaveReqVO req){BpmOADocumentDO old=requireOwner(userId,req.getId());mapper.updateById(BeanUtils.toBean(req,BpmOADocumentDO.class).setId(old.getId()).setOwnerUserId(old.getOwnerUserId()));}
 @Override public void archive(Long userId,Long id){requireOwner(userId,id);mapper.updateById(new BpmOADocumentDO().setId(id).setStatus(10));}
 @Override public List<BpmOADocumentDO> list(Long userId,Long parentId){return mapper.selectVisible(userId,parentId);}
 @Override public BpmOADocumentDO get(Long userId,Long id){BpmOADocumentDO row=mapper.selectById(id);if(row==null||(!userId.equals(row.getOwnerUserId())&&!Integer.valueOf(0).equals(row.getVisibility())))throw exception(OA_TASK_NOT_EXISTS);return row;}
 @Override @Transactional public Long addVersion(Long userId,Long documentId,Long fileId,String summary){BpmOADocumentDO row=requireOwner(userId,documentId);int version=row.getCurrentVersion()+1;BpmOADocumentVersionDO v=new BpmOADocumentVersionDO().setDocumentId(documentId).setVersion(version).setFileId(fileId).setChangeSummary(summary).setCreatedBy(userId);versionMapper.insert(v);mapper.updateById(new BpmOADocumentDO().setId(documentId).setCurrentVersion(version));return v.getId();}
 @Override public List<BpmOADocumentVersionDO> versions(Long userId,Long documentId){get(userId,documentId);return versionMapper.selectList(BpmOADocumentVersionDO::getDocumentId,documentId);}
 @Override public void addMember(Long userId,Long documentId,Long memberId,Integer permission){requireOwner(userId,documentId);memberMapper.insert(new BpmOADocumentMemberDO().setDocumentId(documentId).setUserId(memberId).setPermission(permission));}
 private BpmOADocumentDO requireOwner(Long userId,Long id){BpmOADocumentDO row=mapper.selectById(id);if(row==null||!userId.equals(row.getOwnerUserId()))throw exception(OA_TASK_NOT_EXISTS);return row;}
}
